apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-model-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 4Gi
  volumeName: llm-model-pv
  storageClassName: hostpath
